name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 12266719
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true
        packages: |
          platform-tools
          platforms;android-33
          build-tools;33.0.2

    - name: Accept all SDK licenses
      run: yes | sdkmanager --licenses

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Validate AndroidManifest.xml
      run: xmllint --noout app/src/main/AndroidManifest.xml

    - name: Build APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NetGuardDNS-APK
        path: app/build/outputs/apk/release/app-release.apk
