name: Build APK (Signed)

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout source code
    - name: Checkout source
      uses: actions/checkout@v4

    # 2. Cache Gradle & Android SDK
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Cache Android SDK
      uses: actions/cache@v4
      with:
        path: ~/.android
        key: android-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          android-${{ runner.os }}-

    # 3. Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 4. Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # 5. Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 6. Decode keystore to app folder
    - name: Decode keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/my-release-key.jks

    # 7. Build signed APK using environment variables
    - name: Build signed APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew clean assembleRelease

    # 8. Upload APK artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: personaldnsfilter-apk
        path: app/build/outputs/apk/release/*.apk
