name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17
      ANDROID_SDK_VERSION: "33"
      BUILD_TOOLS_VERSION: "33.0.2"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ~/.android
          key: android-${{ runner.os }}-${{ env.ANDROID_SDK_VERSION }}
          restore-keys: android-${{ runner.os }}-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platform-tools
            platforms;android-${{ env.ANDROID_SDK_VERSION }}
            build-tools;${{ env.BUILD_TOOLS_VERSION }}

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetGuardDNS-APK
          path: app/build/outputs/apk/release/app-release.apk
